apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-cache-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: thumbnail-cache
  template:
    metadata:
      labels:
        app: thumbnail-cache
    spec:
      containers:
      - image: ghcr.io/ajayyy/thumbnail-cache@sha256:fbc210079ea7e084ee380acb49d5833a1b8c548f0f83dda9ece4d2fedcada0fd
        name: thumbnail-cache
        volumeMounts:
          - mountPath: "/app/config.yaml"
            name: config
            subPath: config.yaml
          - mountPath: "/app/cache"
            name: cache
        ports:
          - containerPort: 3001
        # livenessProbe:
        #   httpGet:
        #     path: /api/v1/status
        #     port: 3001
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        #   timeoutSeconds: 3
        # readinessProbe:
        #   httpGet:
        #     path: /api/v1/status
        #     port: 3001
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: thumbnail-cache-pvc
        - name: config
          configMap:
            name: thumbnail-cache-config
            items:
              - key: cache-config
                path: config.yaml
      
---
apiVersion: v1
kind: Service
metadata:
  name: thumbnail-cache-service
  labels:
    app: thumbnail-cache
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
    name: web
  selector:
    app: thumbnail-cache
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thumbnail-cache-servicemonitor
  labels:
    app: thumbnail-cache
    release: prometheus-operator
spec:
  endpoints:
  - port: web
    interval: 1m
  selector:
    matchLabels:
      app: thumbnail-cache