apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-cache-deployment
spec:
  replicas: 25
  selector:
    matchLabels:
      app: thumbnail-cache
  template:
    metadata:
      labels:
        app: thumbnail-cache
    spec:
      containers:
      - image: ghcr.io/ajayyy/thumbnail-cache@sha256:189f783a7c73d7ec82927bd839cc62c25882a77f9a8a48bf57a6f5268057e481
        name: thumbnail-cache
        volumeMounts:
          - mountPath: "/app/config.yaml"
            name: config
            subPath: config.yaml
          - mountPath: "/app/cache"
            name: cache
        ports:
          - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 3001
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 3001
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: thumbnail-cache-pvc
        - name: config
          configMap:
            name: thumbnail-cache-config
            items:
              - key: cache-config
                path: config.yaml
      
---
apiVersion: v1
kind: Service
metadata:
  name: thumbnail-cache-service
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: thumbnail-cache