apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-cache-worker-deployment
spec:
  replicas: 25
  selector:
    matchLabels:
      app: thumbnail-cache-worker
  template:
    metadata:
      labels:
        app: thumbnail-cache-worker
    spec:
      containers:
      - image: ghcr.io/ajayyy/thumbnail-cache-worker@sha256:4b6ab05cccdd08032db8f57ded20d183f198e7ebf8dd3fe68c6f1fbb294056e7
        name: thumbnail-cache-worker
        volumeMounts:
          - mountPath: "/app/config.yaml"
            name: config
            subPath: config.yaml
          - mountPath: "/app/cache"
            name: cache
        ports:
          - containerPort: 3002
        livenessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: thumbnail-cache-pvc
        - name: config
          configMap:
            name: thumbnail-cache-config
            items:
              - key: cache-config
                path: config.yaml