apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-cache-worker-deployment
spec:
  replicas: 55 #65 85
  selector:
    matchLabels:
      app: thumbnail-cache-worker
  template:
    metadata:
      labels:
        app: thumbnail-cache-worker
    spec:
      containers:
      - image: ghcr.io/ajayyy/thumbnail-cache-worker@sha256:eab90a0da6408b123d8c69e37acf16335e511bc4c5a4c394a29e770f8495611c
        name: thumbnail-cache-worker
        volumeMounts:
          - mountPath: "/app/config.yaml"
            name: config
            subPath: config.yaml
          - mountPath: "/app/cache"
            name: cache
        ports:
          - containerPort: 3002
        livenessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: thumbnail-cache-pvc
        - name: config
          configMap:
            name: thumbnail-cache-config
            items:
              - key: cache-config
                path: config.yaml