apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-cache-worker-deployment
spec:
  replicas: 75 #115 #75 #65 #70 #20
  selector:
    matchLabels:
      app: thumbnail-cache-worker
  template:
    metadata:
      labels:
        app: thumbnail-cache-worker
    spec:
      containers:
      - image: ghcr.io/ajayyy/thumbnail-cache-worker@sha256:687ce44b1316eb715cfbf50eb3328c2b3f954fe1b2002f8258231269ca3e263f
        name: thumbnail-cache-worker
        volumeMounts:
          - mountPath: "/app/config.yaml"
            name: config
            subPath: config.yaml
          - mountPath: "/app/cache"
            name: cache
        ports:
          - containerPort: 3002
        resources:
          limits:
            memory: 300Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: thumbnail-cache-pvc
        - name: config
          configMap:
            name: thumbnail-cache-config
            items:
              - key: cache-config
                path: config.yaml