apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
# Maybe not needed
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: true