---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:7.0-alpine
        name: redis
        resources:
          requests:
            memory: 5Gi
        volumeMounts:
          - mountPath: "/data"
            name: redis-data
          - mountPath: "/usr/local/etc/redis"
            name: config
        args:
          - "/usr/local/etc/redis/redis.conf"
      volumes:
        - name: redis-data 
          persistentVolumeClaim:
            claimName: redis-pv-claim
        - name: config
          configMap:
            name: redis-config
            items:
            - key: redis-config
              path: redis.conf
      securityContext:
        sysctls:
        - name: net.core.somaxconn
          value: "65535"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis